### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by kottenator** [pytest-dev/pytest-variables#14]
When I do `pytest --variables my.json` I get:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/_pytest/config.py", line 902, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 750, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/pytest_variables/plugin.py", line 59, in pytest_configure
INTERNALERROR>     variables = import_parser(path, *parser_table[ext])
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/pytest_variables/plugin.py", line 41, in import_parser
INTERNALERROR>     return parser_func(mod, path)
INTERNALERROR>   File "/export/home/tomcat/TeamCity/Agent1/work/2404cefabcf6dc0f/test-env/lib/python3.4/site-packages/pytest_variables/plugin.py", line 16, in default
INTERNALERROR>     return module.load(f)
INTERNALERROR>   File "/opt/python-3.4/lib/python3.4/json/__init__.py", line 268, in load
INTERNALERROR>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
INTERNALERROR>   File "/opt/python-3.4/lib/python3.4/json/__init__.py", line 312, in loads
INTERNALERROR>     s.__class__.__name__))
INTERNALERROR> TypeError: the JSON object must be str, not 'bytes'
Process exited with code 3
```

Environment:
* CentOS 6
* Python 3.4
* pytest 3.0.7
* pytest-variables 1.6.0

**Comment by davehunt** [comment]
@vgavro could this be a regression from https://github.com/pytest-dev/pytest-variables/pull/13?

**Comment by davehunt** [comment]
@kottenator I've pushed a fix and tagged for a new release. v1.6.1 should be available soon.

**Comment by kottenator** [comment]
Thanks, @davehunt. I really like `pytest` and `pytest-variables` helps me a lot. Keep doing such a great stuff ;)
